on:
  pull_request:
  push:

name: "PHPUnit"

jobs:
  phpunit:
    name: PHPUnit ${{ matrix.phpunit }} PHP ${{ matrix.php }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
        phpunit:
          - 9
          - 10
          - 11
        exclude:
          - php: "8.0"
            phpunit: 10
          - php: "8.0"
            phpunit: 11
          - php: "8.1"
            phpunit: 11
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: pcov

      - name: Install dependencies
        run: composer install

      - name: Switching PHPUnit version
        run: composer req --dev phpunit/phpunit:^${{ matrix.phpunit }} -W

      - name: Run tests with code coverage.
        run: composer test -- -c phpunit${{ matrix.phpunit }}.xml

      - name: Upload coverage to Codecov.
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
